import Footer from '@/components/Footer';
import '../globals.css'
import { Inter } from '@next/font/google';
import SearchHeader from '@/components/SearchHeader';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Google2.0',
  description: 'Generated by create next app',
}

export default function SearchLayout({ children }) {
  return (
    
      <div className={inter.className}>
        <SearchHeader/>
        {children}
        <Footer/>
      </div>
    
  )
}
